// Check if user input is a single emoji
export const isSingleEmoji = (str: string) => {
    const emojiRegex = /^\p{RGI_Emoji}$/v;
    const result = emojiRegex.test(str.trim());
    return result;
};

// Emoji List
const emojis = [
    // --- Food & Drinks ---
    {
        icon: "🖼",
        title: "Image",
        names: ["Image", "picture", "photo"],
    },
    {
        icon: "🍏",
        title: "Green Apple",
        names: ["Green Apple", "apple", "fruit", "green"],
    },
    {
        icon: "🍎",
        title: "Red Apple",
        names: ["Red Apple", "apple", "fruit", "red"],
    },
    { icon: "🍐", title: "Pear", names: ["Pear", "fruit"] },
    { icon: "🍊", title: "Tangerine", names: ["Tangerine", "fruit", "orange"] },
    { icon: "🍋", title: "Lemon", names: ["Lemon", "citrus", "fruit"] },
    { icon: "🍌", title: "Banana", names: ["Banana", "fruit"] },
    {
        icon: "🍉",
        title: "Watermelon",
        names: ["Watermelon", "fruit", "melon"],
    },
    { icon: "🍇", title: "Grapes", names: ["Grapes", "fruit", "grape"] },
    {
        icon: "🍓",
        title: "Strawberry",
        names: ["Strawberry", "berry", "fruit"],
    },
    { icon: "🍈", title: "Melon", names: ["Melon", "fruit"] },
    {
        icon: "🍒",
        title: "Cherries",
        names: ["Cherries", "berry", "cherry", "fruit"],
    },
    { icon: "🍑", title: "Peach", names: ["Peach", "fruit"] },
    { icon: "🥭", title: "Mango", names: ["Mango", "fruit", "tropical"] },
    {
        icon: "🍍",
        title: "Pineapple",
        names: ["Pineapple", "fruit", "tropical"],
    },
    {
        icon: "🥥",
        title: "Coconut",
        names: ["Coconut", "piña colada", "tropical"],
    },
    {
        icon: "🥝",
        title: "Kiwi Fruit",
        names: ["Kiwi Fruit", "food", "fruit", "kiwi"],
    },
    { icon: "🍅", title: "Tomato", names: ["Tomato", "vegetable"] },
    { icon: "🥑", title: "Avocado", names: ["Avocado", "food", "fruit"] },
    {
        icon: "🍆",
        title: "Eggplant",
        names: ["Eggplant", "aubergine", "vegetable"],
    },
    { icon: "🥔", title: "Potato", names: ["Potato", "food", "vegetable"] },
    { icon: "🥕", title: "Carrot", names: ["Carrot", "food", "vegetable"] },
    {
        icon: "🌽",
        title: "Ear of Corn",
        names: ["Ear of Corn", "corn", "maze"],
    },
    {
        icon: "🌶️",
        title: "Hot Pepper",
        names: ["Hot Pepper", "chili", "pepper", "spicy"],
    },
    {
        icon: "🥒",
        title: "Cucumber",
        names: ["Cucumber", "food", "pickle", "vegetable"],
    },
    {
        icon: "🥬",
        title: "Leafy Green",
        names: ["Leafy Green", "bokeh", "kale", "lettuce", "spinach"],
    },
    { icon: "🥦", title: "Broccoli", names: ["Broccoli", "wild cabbage"] },
    { icon: "🧄", title: "Garlic", names: ["Garlic", "flavoring"] },
    { icon: "🧅", title: "Onion", names: ["Onion", "flavoring"] },
    { icon: "🍄", title: "Mushroom", names: ["Mushroom", "toadstool"] },
    {
        icon: "🥜",
        title: "Peanuts",
        names: ["Peanuts", "food", "nut", "peanut"],
    },
    { icon: "🍞", title: "Bread", names: ["Bread", "loaf"] },
    {
        icon: "🥐",
        title: "Croissant",
        names: ["Croissant", "crescent roll", "french", "pastry"],
    },
    {
        icon: "🥖",
        title: "Baguette Bread",
        names: ["Baguette Bread", "baguette", "bread", "french"],
    },
    { icon: "🥨", title: "Pretzel", names: ["Pretzel", "twisted"] },
    { icon: "🥯", title: "Bagel", names: ["Bagel", "bakery", "bread"] },
    {
        icon: "🥞",
        title: "Pancakes",
        names: ["Pancakes", "crêpe", "food", "hotcake"],
    },
    { icon: "🧇", title: "Waffle", names: ["Waffle", "iron", "pancake"] },
    { icon: "🧀", title: "Cheese Wedge", names: ["Cheese Wedge", "cheese"] },
    {
        icon: "🍖",
        title: "Meat on Bone",
        names: ["Meat on Bone", "bone", "meat"],
    },
    {
        icon: "🍗",
        title: "Poultry Leg",
        names: ["Poultry Leg", "bone", "chicken", "drumstick", "leg"],
    },
    {
        icon: "🥩",
        title: "Cut of Meat",
        names: ["Cut of Meat", "chop", "lambchop", "porkchop", "steak"],
    },
    { icon: "🥓", title: "Bacon", names: ["Bacon", "food", "meat", "pork"] },
    {
        icon: "🍔",
        title: "Hamburger",
        names: ["Hamburger", "burger", "fast food"],
    },
    {
        icon: "🍟",
        title: "French Fries",
        names: ["French Fries", "french", "fries"],
    },
    { icon: "🍕", title: "Pizza", names: ["Pizza", "cheese", "slice"] },
    {
        icon: "🌭",
        title: "Hot Dog",
        names: ["Hot Dog", "frankfurter", "sausage"],
    },
    { icon: "🥪", title: "Sandwich", names: ["Sandwich", "bread"] },
    { icon: "🌮", title: "Taco", names: ["Taco", "mexican"] },
    { icon: "🌯", title: "Burrito", names: ["Burrito", "mexican", "wrap"] },
    {
        icon: "🥙",
        title: "Stuffed Flatbread",
        names: [
            "Stuffed Flatbread",
            "falafel",
            "flatbread",
            "gyro",
            "shawarma",
        ],
    },
    {
        icon: "🧆",
        title: "Falafel",
        names: ["Falafel", "chickpea", "meatball"],
    },
    {
        icon: "🍳",
        title: "Cooking",
        names: ["Cooking", "egg", "frying", "pan"],
    },
    {
        icon: "🥘",
        title: "Shallow Pan of Food",
        names: ["Shallow Pan of Food", "casserole", "paella", "pan"],
    },
    { icon: "🍲", title: "Pot of Food", names: ["Pot of Food", "pot", "stew"] },
    {
        icon: "🥣",
        title: "Bowl with Spoon",
        names: ["Bowl with Spoon", "breakfast", "cereal", "congee"],
    },
    {
        icon: "🥗",
        title: "Green Salad",
        names: ["Green Salad", "food", "green", "salad"],
    },
    { icon: "🍿", title: "Popcorn", names: ["Popcorn", "snack"] },
    { icon: "🧈", title: "Butter", names: ["Butter", "dairy"] },
    { icon: "🧂", title: "Salt", names: ["Salt", "condiment", "shaker"] },
    { icon: "🥫", title: "Canned Food", names: ["Canned Food", "can"] },
    { icon: "🍱", title: "Bento Box", names: ["Bento Box", "bento", "box"] },
    {
        icon: "🍘",
        title: "Rice Cracker",
        names: ["Rice Cracker", "cracker", "rice"],
    },
    {
        icon: "🍙",
        title: "Rice Ball",
        names: ["Rice Ball", "japanese", "rice"],
    },
    {
        icon: "🍚",
        title: "Cooked Rice",
        names: ["Cooked Rice", "cooked", "rice"],
    },
    { icon: "🍛", title: "Curry Rice", names: ["Curry Rice", "curry", "rice"] },
    {
        icon: "🍜",
        title: "Steaming Bowl",
        names: ["Steaming Bowl", "noodle", "ramen", "soup"],
    },
    { icon: "🍝", title: "Spaghetti", names: ["Spaghetti", "pasta"] },
    {
        icon: "🍠",
        title: "Roasted Sweet Potato",
        names: ["Roasted Sweet Potato", "potato", "roasted", "sweet"],
    },
    { icon: "🍢", title: "Oden", names: ["Oden", "seafood", "skewer"] },
    { icon: "🍣", title: "Sushi", names: ["Sushi", "fish", "japanese"] },
    {
        icon: "🍤",
        title: "Fried Shrimp",
        names: ["Fried Shrimp", "fried", "prawn", "shrimp", "tempura"],
    },
    {
        icon: "🍥",
        title: "Fish Cake with Swirl",
        names: ["Fish Cake with Swirl", "cake", "fish", "swirl"],
    },
    {
        icon: "🥮",
        title: "Mooncake",
        names: ["Mooncake", "autumn", "festival"],
    },
    {
        icon: "🍡",
        title: "Dango",
        names: ["Dango", "dessert", "japanese", "skewered"],
    },
    {
        icon: "🥟",
        title: "Dumpling",
        names: ["Dumpling", "empanada", "gyoza", "jiaozi", "pierogi"],
    },
    {
        icon: "🥠",
        title: "Fortune Cookie",
        names: ["Fortune Cookie", "cookie", "prophecy"],
    },
    { icon: "🥡", title: "Takeout Box", names: ["Takeout Box", "oyster pail"] },
    {
        icon: "🍦",
        title: "Soft Ice Cream",
        names: ["Soft Ice Cream", "cream", "ice", "soft", "sweet"],
    },
    {
        icon: "🍧",
        title: "Shaved Ice",
        names: ["Shaved Ice", "dessert", "ice", "shaved", "sweet"],
    },
    {
        icon: "🍨",
        title: "Ice Cream",
        names: ["Ice Cream", "cream", "dessert", "ice", "sweet"],
    },
    {
        icon: "🍩",
        title: "Doughnut",
        names: ["Doughnut", "dessert", "donut", "sweet"],
    },
    { icon: "🍪", title: "Cookie", names: ["Cookie", "dessert", "sweet"] },
    {
        icon: "🎂",
        title: "Birthday Cake",
        names: ["Birthday Cake", "birthday", "cake", "celebration", "dessert"],
    },
    {
        icon: "🍰",
        title: "Shortcake",
        names: ["Shortcake", "cake", "dessert", "slice", "sweet"],
    },
    { icon: "🧁", title: "Cupcake", names: ["Cupcake", "bakery", "sweet"] },
    { icon: "🥧", title: "Pie", names: ["Pie", "bakery", "filling", "pastry"] },
    {
        icon: "🍫",
        title: "Chocolate Bar",
        names: ["Chocolate Bar", "bar", "chocolate", "dessert", "sweet"],
    },
    { icon: "🍬", title: "Candy", names: ["Candy", "dessert", "sweet"] },
    {
        icon: "🍭",
        title: "Lollipop",
        names: ["Lollipop", "candy", "dessert", "sweet"],
    },
    {
        icon: "🍮",
        title: "Custard",
        names: ["Custard", "dessert", "pudding", "sweet"],
    },
    {
        icon: "🍯",
        title: "Honey Pot",
        names: ["Honey Pot", "honey", "honeypot", "pot", "sweet"],
    },
    {
        icon: "🍼",
        title: "Baby Bottle",
        names: ["Baby Bottle", "baby", "bottle", "drink", "milk"],
    },
    {
        icon: "🥛",
        title: "Glass of Milk",
        names: ["Glass of Milk", "drink", "glass", "milk"],
    },
    {
        icon: "☕",
        title: "Hot Beverage",
        names: ["Hot Beverage", "beverage", "coffee", "drink", "hot", "tea"],
    },
    {
        icon: "🍵",
        title: "Teacup Without Handle",
        names: [
            "Teacup Without Handle",
            "beverage",
            "cup",
            "drink",
            "matcha",
            "tea",
        ],
    },
    {
        icon: "🍶",
        title: "Sake",
        names: ["Sake", "bar", "beverage", "bottle", "cup", "drink"],
    },
    {
        icon: "🍾",
        title: "Bottle with Popping Cork",
        names: [
            "Bottle with Popping Cork",
            "bar",
            "bottle",
            "champagne",
            "drink",
            "popping",
        ],
    },
    {
        icon: "🍷",
        title: "Wine Glass",
        names: ["Wine Glass", "bar", "beverage", "drink", "glass", "wine"],
    },
    {
        icon: "🍸",
        title: "Cocktail Glass",
        names: ["Cocktail Glass", "bar", "cocktail", "drink", "glass"],
    },
    {
        icon: "🍹",
        title: "Tropical Drink",
        names: ["Tropical Drink", "bar", "drink", "tropical"],
    },
    {
        icon: "🍺",
        title: "Beer Mug",
        names: ["Beer Mug", "bar", "beer", "drink", "mug"],
    },
    {
        icon: "🍻",
        title: "Clinking Beer Mugs",
        names: [
            "Clinking Beer Mugs",
            "bar",
            "beer",
            "clinking",
            "drink",
            "mug",
        ],
    },
    {
        icon: "🥂",
        title: "Clinking Glasses",
        names: ["Clinking Glasses", "celebrate", "clinking", "drink", "glass"],
    },
    {
        icon: "🥃",
        title: "Whisky Glass",
        names: ["Whisky Glass", "liquor", "shot", "whisky"],
    },
    {
        icon: "🥤",
        title: "Cup with Straw",
        names: ["Cup with Straw", "juice", "soda"],
    },
    { icon: "🧃", title: "Beverage Box", names: ["Beverage Box", "juice box"] },

    // --- Housing, Utilities & Travel ---
    {
        icon: "🏠",
        title: "House",
        names: ["House", "home", "rent", "mortgage", "building"],
    },
    {
        icon: "🏡",
        title: "House with Garden",
        names: ["House with Garden", "home", "house", "garden"],
    },
    {
        icon: "🏢",
        title: "Office Building",
        names: ["Office Building", "building", "work", "corporate"],
    },
    {
        icon: "🏣",
        title: "Japanese Post Office",
        names: ["Japanese Post Office", "building", "japanese", "post"],
    },
    {
        icon: "🏥",
        title: "Hospital",
        names: ["Hospital", "doctor", "medicine", "health"],
    },
    {
        icon: "🏨",
        title: "Hotel",
        names: ["Hotel", "building", "vacation", "resort"],
    },
    {
        icon: "🏬",
        title: "Department Store",
        names: ["Department Store", "building", "store", "shopping"],
    },
    {
        icon: "🏫",
        title: "School",
        names: ["School", "building", "education", "learn"],
    },
    { icon: "🏬", title: "Store", names: ["Store", "shop", "retail"] },
    {
        icon: "🏭",
        title: "Factory",
        names: ["Factory", "building", "industry"],
    },
    { icon: "🏰", title: "Castle", names: ["Castle", "building", "fortress"] },
    { icon: "💒", title: "Wedding", names: ["Wedding", "chapel", "romance"] },
    {
        icon: "🗼",
        title: "Tokyo Tower",
        names: ["Tokyo Tower", "tokyo", "tower"],
    },
    {
        icon: "🗽",
        title: "Statue of Liberty",
        names: ["Statue of Liberty", "liberty", "statue"],
    },
    {
        icon: "⛪",
        title: "Church",
        names: ["Church", "christian", "cross", "religion"],
    },
    {
        icon: "🕌",
        title: "Mosque",
        names: ["Mosque", "islam", "muslim", "religion"],
    },
    {
        icon: "🛕",
        title: "Hindu Temple",
        names: ["Hindu Temple", "hindu", "religion", "temple"],
    },
    {
        icon: "🕍",
        title: "Synagogue",
        names: ["Synagogue", "jewish", "religion", "temple"],
    },
    {
        icon: "⛩️",
        title: "Shinto Shrine",
        names: ["Shinto Shrine", "religion", "shinto", "shrine"],
    },
    {
        icon: "🕋",
        title: "Kaaba",
        names: ["Kaaba", "islam", "muslim", "religion"],
    },
    {
        icon: "⚡",
        title: "High Voltage",
        names: [
            "High Voltage",
            "electricity",
            "energy",
            "light",
            "power",
            "utility",
        ],
    },
    {
        icon: "💧",
        title: "Droplet",
        names: ["Droplet", "cold", "water", "sweat", "utility", "plumbing"],
    },
    {
        icon: "🔥",
        title: "Fire",
        names: ["Fire", "flame", "gas", "heating", "hot"],
    },
    {
        icon: "🌐",
        title: "Globe with Meridians",
        names: ["Globe with Meridians", "internet", "network", "web", "wifi"],
    },
    {
        icon: "📶",
        title: "Antenna Bars",
        names: ["Antenna Bars", "bars", "cell", "signal", "mobile"],
    },
    {
        icon: "🚗",
        title: "Automobile",
        names: ["Automobile", "car", "driving", "vehicle", "transport"],
    },
    { icon: "🚕", title: "Taxi", names: ["Taxi", "cab", "uber", "ride"] },
    {
        icon: "🚙",
        title: "Sport Utility Vehicle",
        names: ["Sport Utility Vehicle", "suv", "car"],
    },
    {
        icon: "🚌",
        title: "Bus",
        names: ["Bus", "commute", "transit", "public transport"],
    },
    { icon: "🚎", title: "Trolleybus", names: ["Trolleybus", "bus", "tram"] },
    {
        icon: "🏎️",
        title: "Racing Car",
        names: ["Racing Car", "car", "racing", "fast"],
    },
    {
        icon: "🚓",
        title: "Police Car",
        names: ["Police Car", "car", "patrol", "police"],
    },
    {
        icon: "🚑",
        title: "Ambulance",
        names: ["Ambulance", "emergency", "health", "vehicle"],
    },
    {
        icon: "🚒",
        title: "Fire Engine",
        names: ["Fire Engine", "engine", "fire", "truck"],
    },
    { icon: "🚐", title: "Minibus", names: ["Minibus", "bus", "van"] },
    {
        icon: "🚚",
        title: "Delivery Truck",
        names: ["Delivery Truck", "delivery", "truck"],
    },
    {
        icon: "🚛",
        title: "Articulated Lorry",
        names: ["Articulated Lorry", "lorry", "semi", "truck"],
    },
    { icon: "🚜", title: "Tractor", names: ["Tractor", "agriculture", "farm"] },
    {
        icon: "🛵",
        title: "Motor Scooter",
        names: ["Motor Scooter", "moped", "scooter"],
    },
    { icon: "🏍️", title: "Motorcycle", names: ["Motorcycle", "bike"] },
    {
        icon: "🛺",
        title: "Auto Rickshaw",
        names: ["Auto Rickshaw", "rickshaw", "tuk tuk"],
    },
    { icon: "🚲", title: "Bicycle", names: ["Bicycle", "bike", "cycle"] },
    {
        icon: "🛴",
        title: "Kick Scooter",
        names: ["Kick Scooter", "kick", "scooter"],
    },
    {
        icon: "⛽",
        title: "Fuel Pump",
        names: ["Fuel Pump", "fuel", "gas", "petrol", "station"],
    },
    {
        icon: "🚨",
        title: "Police Car Light",
        names: ["Police Car Light", "beacon", "emergency", "light"],
    },
    {
        icon: "✈️",
        title: "Airplane",
        names: ["Airplane", "flight", "plane", "travel", "vacation"],
    },
    {
        icon: "🛫",
        title: "Airplane Departure",
        names: ["Airplane Departure", "check-in", "departure", "flight"],
    },
    {
        icon: "🛬",
        title: "Airplane Arrival",
        names: ["Airplane Arrival", "arrival", "landing", "plane"],
    },
    { icon: "🚀", title: "Rocket", names: ["Rocket", "launch", "space"] },
    {
        icon: "🛸",
        title: "Flying Saucer",
        names: ["Flying Saucer", "ufo", "alien"],
    },
    { icon: "🚁", title: "Helicopter", names: ["Helicopter", "copter"] },
    {
        icon: "⛵",
        title: "Sailboat",
        names: ["Sailboat", "boat", "sea", "yacht"],
    },
    { icon: "🚤", title: "Speedboat", names: ["Speedboat", "boat"] },
    {
        icon: "🛳️",
        title: "Passenger Ship",
        names: ["Passenger Ship", "cruise", "ship"],
    },
    { icon: "⚓", title: "Anchor", names: ["Anchor", "ship", "boat"] },
    {
        icon: "🧳",
        title: "Luggage",
        names: ["Luggage", "baggage", "packing", "travel"],
    },

    // --- Health, Personal & Clothing ---
    {
        icon: "💊",
        title: "Pill",
        names: ["Pill", "doctor", "health", "medicine", "pharmacy"],
    },
    {
        icon: "🩺",
        title: "Stethoscope",
        names: ["Stethoscope", "doctor", "heart", "medicine"],
    },
    {
        icon: "🩹",
        title: "Adhesive Bandage",
        names: ["Adhesive Bandage", "bandage", "heal", "patch"],
    },
    {
        icon: "💉",
        title: "Syringe",
        names: [
            "Syringe",
            "doctor",
            "injection",
            "medicine",
            "needle",
            "vaccine",
        ],
    },
    {
        icon: "🩸",
        title: "Drop of Blood",
        names: ["Drop of Blood", "blood", "bleed", "injury"],
    },
    {
        icon: "🧬",
        title: "DNA",
        names: ["DNA", "biologist", "evolution", "gene", "genetics"],
    },
    {
        icon: "🔬",
        title: "Microscope",
        names: ["Microscope", "laboratory", "science"],
    },
    {
        icon: "🔭",
        title: "Telescope",
        names: ["Telescope", "astronomy", "science", "space"],
    },
    {
        icon: "👓",
        title: "Glasses",
        names: ["Glasses", "clothing", "eye", "eyeglasses", "specs"],
    },
    {
        icon: "🕶️",
        title: "Sunglasses",
        names: ["Sunglasses", "dark", "eyewear", "glasses"],
    },
    {
        icon: "🥽",
        title: "Goggles",
        names: ["Goggles", "eye protection", "swimming", "welding"],
    },
    {
        icon: "🥼",
        title: "Lab Coat",
        names: ["Lab Coat", "doctor", "experiment", "scientist"],
    },
    {
        icon: "🦺",
        title: "Safety Vest",
        names: ["Safety Vest", "emergency", "safety", "vest"],
    },
    {
        icon: "👔",
        title: "Necktie",
        names: ["Necktie", "clothing", "necktie", "suit", "work"],
    },
    {
        icon: "👕",
        title: "T-Shirt",
        names: ["T-Shirt", "clothing", "shirt", "tshirt"],
    },
    {
        icon: "👖",
        title: "Jeans",
        names: ["Jeans", "clothing", "pants", "trousers"],
    },
    { icon: "🧣", title: "Scarf", names: ["Scarf", "clothes", "cold", "neck"] },
    { icon: "🧤", title: "Gloves", names: ["Gloves", "clothes", "hands"] },
    { icon: "🧥", title: "Coat", names: ["Coat", "jacket", "warm"] },
    { icon: "🧦", title: "Socks", names: ["Socks", "clothes", "feet"] },
    { icon: "👗", title: "Dress", names: ["Dress", "clothing", "fashion"] },
    { icon: "👘", title: "Kimono", names: ["Kimono", "clothing", "japanese"] },
    {
        icon: "🥻",
        title: "Saree",
        names: ["Saree", "clothing", "dress", "india"],
    },
    {
        icon: "🩱",
        title: "One-Piece Swimsuit",
        names: ["One-Piece Swimsuit", "bathing suit", "swimsuit"],
    },
    {
        icon: "🩲",
        title: "Briefs",
        names: ["Briefs", "bathing suit", "underwear"],
    },
    { icon: "🩳", title: "Shorts", names: ["Shorts", "bathing suit", "pants"] },
    { icon: "👙", title: "Bikini", names: ["Bikini", "clothing", "swimsuit"] },
    {
        icon: "👛",
        title: "Purse",
        names: ["Purse", "accessory", "bag", "coin"],
    },
    {
        icon: "👜",
        title: "Handbag",
        names: ["Handbag", "accessory", "bag", "purse"],
    },
    { icon: "👝", title: "Clutch Bag", names: ["Clutch Bag", "bag", "pouch"] },
    {
        icon: "🎒",
        title: "School Backpack",
        names: ["School Backpack", "backpack", "bag", "school"],
    },
    {
        icon: "👞",
        title: "Man's Shoe",
        names: ["Man's Shoe", "clothing", "shoe", "style"],
    },
    {
        icon: "👟",
        title: "Running Shoe",
        names: ["Running Shoe", "athletic", "shoe", "sneaker"],
    },
    {
        icon: "🥾",
        title: "Hiking Boot",
        names: ["Hiking Boot", "backpacking", "boot", "camping", "hiking"],
    },
    {
        icon: "🥿",
        title: "Flat Shoe",
        names: ["Flat Shoe", "ballet flat", "slip-on"],
    },
    {
        icon: "👠",
        title: "High-Heeled Shoe",
        names: ["High-Heeled Shoe", "clothing", "heel", "shoe"],
    },
    {
        icon: "👡",
        title: "Woman's Sandal",
        names: ["Woman's Sandal", "sandal", "shoe"],
    },
    {
        icon: "🩰",
        title: "Ballet Shoes",
        names: ["Ballet Shoes", "dance", "ballet"],
    },
    {
        icon: "👢",
        title: "Woman's Boot",
        names: ["Woman's Boot", "boot", "shoe"],
    },
    { icon: "👑", title: "Crown", names: ["Crown", "king", "queen", "royal"] },
    {
        icon: "👒",
        title: "Woman's Hat",
        names: ["Woman's Hat", "clothing", "hat"],
    },
    {
        icon: "🎩",
        title: "Top Hat",
        names: ["Top Hat", "clothing", "hat", "tophat"],
    },
    {
        icon: "🎓",
        title: "Graduation Cap",
        names: [
            "Graduation Cap",
            "cap",
            "celebration",
            "clothing",
            "graduation",
        ],
    },
    { icon: "🧢", title: "Billed Cap", names: ["Billed Cap", "baseball cap"] },
    {
        icon: "💄",
        title: "Lipstick",
        names: ["Lipstick", "cosmetics", "makeup"],
    },
    {
        icon: "💍",
        title: "Ring",
        names: ["Ring", "diamond", "jewelry", "marriage"],
    },
    {
        icon: "💈",
        title: "Barber Pole",
        names: ["Barber Pole", "barber", "haircut", "salon"],
    },

    // --- Finance, Money & Shopping ---
    {
        icon: "💰",
        title: "Money Bag",
        names: [
            "Money Bag",
            "bag",
            "dollar",
            "money",
            "rich",
            "salary",
            "cash",
        ],
    },
    {
        icon: "💴",
        title: "Yen Banknote",
        names: ["Yen Banknote", "banknote", "bill", "currency", "money", "yen"],
    },
    {
        icon: "💵",
        title: "Dollar Banknote",
        names: [
            "Dollar Banknote",
            "banknote",
            "bill",
            "currency",
            "dollar",
            "money",
        ],
    },
    {
        icon: "💶",
        title: "Euro Banknote",
        names: [
            "Euro Banknote",
            "banknote",
            "bill",
            "currency",
            "euro",
            "money",
        ],
    },
    {
        icon: "💷",
        title: "Pound Banknote",
        names: [
            "Pound Banknote",
            "banknote",
            "bill",
            "currency",
            "money",
            "pound",
        ],
    },
    {
        icon: "💸",
        title: "Money with Wings",
        names: [
            "Money with Wings",
            "banknote",
            "bill",
            "fly",
            "money",
            "spend",
        ],
    },
    {
        icon: "💳",
        title: "Credit Card",
        names: ["Credit Card", "bank", "card", "credit", "money", "payment"],
    },
    {
        icon: "🧾",
        title: "Receipt",
        names: ["Receipt", "accounting", "bookkeeping", "proof", "tax", "bill"],
    },
    {
        icon: "📈",
        title: "Chart Increasing",
        names: [
            "Chart Increasing",
            "chart",
            "graph",
            "growth",
            "stocks",
            "profit",
        ],
    },
    {
        icon: "📉",
        title: "Chart Decreasing",
        names: [
            "Chart Decreasing",
            "chart",
            "down",
            "graph",
            "loss",
            "expense",
        ],
    },
    {
        icon: "🏦",
        title: "Bank",
        names: ["Bank", "building", "finance", "institution"],
    },
    {
        icon: "💎",
        title: "Gem Stone",
        names: ["Gem Stone", "diamond", "gem", "jewel", "wealth", "luxury"],
    },
    {
        icon: "⚖️",
        title: "Balance Scale",
        names: ["Balance Scale", "balance", "justice", "scale", "weight"],
    },
    {
        icon: "🛒",
        title: "Shopping Cart",
        names: ["Shopping Cart", "cart", "groceries", "shopping", "buy"],
    },
    {
        icon: "🛍️",
        title: "Shopping Bags",
        names: ["Shopping Bags", "bag", "hotel", "shopping", "retail"],
    },
    { icon: "🏷️", title: "Label", names: ["Label", "tag", "price", "sale"] },
    {
        icon: "🏧",
        title: "ATM Sign",
        names: ["ATM Sign", "atm", "automated", "bank", "cash"],
    },
    {
        icon: "🏧",
        title: "Automated Teller Machine",
        names: ["Automated Teller Machine", "cash", "withdraw"],
    },

    // --- Tech & Electronics ---
    {
        icon: "📱",
        title: "Mobile Phone",
        names: ["Mobile Phone", "cell", "mobile", "phone", "smartphone"],
    },
    {
        icon: "📲",
        title: "Mobile Phone with Arrow",
        names: ["Mobile Phone with Arrow", "call", "cell", "mobile"],
    },
    {
        icon: "💻",
        title: "Laptop",
        names: ["Laptop", "computer", "pc", "personal", "tech", "work"],
    },
    {
        icon: "🖥️",
        title: "Desktop Computer",
        names: ["Desktop Computer", "computer", "desktop", "monitor"],
    },
    { icon: "🖨️", title: "Printer", names: ["Printer", "computer", "paper"] },
    { icon: "⌨️", title: "Keyboard", names: ["Keyboard", "computer", "type"] },
    {
        icon: "🖱️",
        title: "Computer Mouse",
        names: ["Computer Mouse", "click", "computer", "mouse"],
    },

    {
        icon: "💽",
        title: "Computer Disk",
        names: ["Computer Disk", "computer", "disk", "minidisc"],
    },
    {
        icon: "💾",
        title: "Floppy Disk",
        names: ["Floppy Disk", "computer", "disk", "save"],
    },
    {
        icon: "💿",
        title: "Optical Disk",
        names: ["Optical Disk", "cd", "computer", "disk"],
    },
    { icon: "📀", title: "DVD", names: ["DVD", "bluray", "dvd", "optical"] },
    { icon: "📷", title: "Camera", names: ["Camera", "photo", "picture"] },
    {
        icon: "📸",
        title: "Camera with Flash",
        names: ["Camera with Flash", "camera", "flash", "photo"],
    },
    {
        icon: "📹",
        title: "Video Camera",
        names: ["Video Camera", "camera", "video"],
    },
    {
        icon: "🎥",
        title: "Movie Camera",
        names: ["Movie Camera", "cinema", "movie", "video"],
    },
    {
        icon: "📞",
        title: "Telephone Receiver",
        names: ["Telephone Receiver", "phone", "receiver", "telephone"],
    },
    { icon: "☎️", title: "Telephone", names: ["Telephone", "phone"] },
    { icon: "📟", title: "Pager", names: ["Pager", "beeper"] },
    { icon: "📠", title: "Fax Machine", names: ["Fax Machine", "fax"] },
    { icon: "📺", title: "Television", names: ["Television", "tv", "video"] },
    { icon: "📻", title: "Radio", names: ["Radio", "audio", "station"] },
    {
        icon: "🎙️",
        title: "Studio Microphone",
        names: ["Studio Microphone", "mic", "microphone", "music"],
    },
    {
        icon: "🎚️",
        title: "Level Slider",
        names: ["Level Slider", "level", "slider"],
    },
    {
        icon: "🎛️",
        title: "Control Knobs",
        names: ["Control Knobs", "control", "knobs"],
    },
    { icon: "⏱️", title: "Stopwatch", names: ["Stopwatch", "clock", "time"] },
    {
        icon: "⏲️",
        title: "Timer Clock",
        names: ["Timer Clock", "clock", "timer"],
    },
    {
        icon: "⏰",
        title: "Alarm Clock",
        names: ["Alarm Clock", "alarm", "clock"],
    },
    {
        icon: "🕰️",
        title: "Mantelpiece Clock",
        names: ["Mantelpiece Clock", "clock"],
    },
    {
        icon: "💡",
        title: "Light Bulb",
        names: ["Light Bulb", "bulb", "idea", "light"],
    },
    {
        icon: "🔦",
        title: "Flashlight",
        names: ["Flashlight", "electric", "light", "torch"],
    },

    // --- Entertainment, Games & Sports ---
    {
        icon: "🎮",
        title: "Video Game",
        names: [
            "Video Game",
            "controller",
            "game",
            "gaming",
            "playstation",
            "xbox",
        ],
    },
    {
        icon: "🕹️",
        title: "Joystick",
        names: ["Joystick", "game", "gaming", "retro"],
    },
    {
        icon: "🎲",
        title: "Game Die",
        names: ["Game Die", "dice", "die", "game"],
    },
    {
        icon: "🧩",
        title: "Jigsaw",
        names: ["Jigsaw", "clue", "interlocking", "puzzle"],
    },
    {
        icon: "🎯",
        title: "Bullseye",
        names: ["Bullseye", "target", "dart", "game"],
    },
    { icon: "🎳", title: "Bowling", names: ["Bowling", "ball", "game", "pin"] },
    { icon: "🪀", title: "Yo-Yo", names: ["Yo-Yo", "toy"] },
    { icon: "🪁", title: "Kite", names: ["Kite", "fly", "toy"] },
    {
        icon: "🔮",
        title: "Crystal Ball",
        names: ["Crystal Ball", "ball", "crystal", "fortune", "magic"],
    },
    {
        icon: "🎨",
        title: "Artist Palette",
        names: ["Artist Palette", "art", "museum", "paint", "palette"],
    },
    {
        icon: "🎬",
        title: "Clapper Board",
        names: ["Clapper Board", "clapper", "movie", "film"],
    },
    {
        icon: "🎤",
        title: "Microphone",
        names: ["Microphone", "karaoke", "mic", "sing"],
    },
    {
        icon: "🎧",
        title: "Headphone",
        names: ["Headphone", "earphone", "music", "audio"],
    },
    {
        icon: "🎼",
        title: "Musical Score",
        names: ["Musical Score", "clef", "music", "score"],
    },
    {
        icon: "🎵",
        title: "Musical Note",
        names: ["Musical Note", "music", "note"],
    },
    {
        icon: "🎶",
        title: "Musical Notes",
        names: ["Musical Notes", "music", "notes", "song"],
    },
    {
        icon: "🎷",
        title: "Saxophone",
        names: ["Saxophone", "instrument", "music", "sax"],
    },
    { icon: "🎸", title: "Guitar", names: ["Guitar", "instrument", "music"] },
    {
        icon: "🎹",
        title: "Musical Keyboard",
        names: ["Musical Keyboard", "instrument", "keyboard", "piano"],
    },
    { icon: "🎺", title: "Trumpet", names: ["Trumpet", "brass", "music"] },
    { icon: "🎻", title: "Violin", names: ["Violin", "instrument", "music"] },
    { icon: "🥁", title: "Drum", names: ["Drum", "drumsticks", "music"] },
    {
        icon: "⚽",
        title: "Soccer Ball",
        names: ["Soccer Ball", "ball", "football", "soccer"],
    },
    { icon: "🏀", title: "Basketball", names: ["Basketball", "ball", "hoop"] },
    {
        icon: "🏈",
        title: "American Football",
        names: ["American Football", "american", "ball", "football"],
    },
    { icon: "⚾", title: "Baseball", names: ["Baseball", "ball"] },
    { icon: "🥎", title: "Softball", names: ["Softball", "ball", "underarm"] },
    { icon: "🎾", title: "Tennis", names: ["Tennis", "ball", "racket"] },
    { icon: "🏐", title: "Volleyball", names: ["Volleyball", "ball", "game"] },
    {
        icon: "🏉",
        title: "Rugby Football",
        names: ["Rugby Football", "ball", "rugby"],
    },
    { icon: "🥏", title: "Flying Disc", names: ["Flying Disc", "frisbee"] },
    {
        icon: "🎱",
        title: "Pool 8 Ball",
        names: ["Pool 8 Ball", "8", "ball", "billiards", "eight", "game"],
    },
    {
        icon: "🏓",
        title: "Ping Pong",
        names: ["Ping Pong", "ball", "bat", "paddle", "table tennis"],
    },
    {
        icon: "🏸",
        title: "Badminton",
        names: ["Badminton", "birdie", "racket", "shuttlecock"],
    },
    {
        icon: "🏒",
        title: "Ice Hockey",
        names: ["Ice Hockey", "game", "hockey", "ice", "puck"],
    },
    {
        icon: "🏑",
        title: "Field Hockey",
        names: ["Field Hockey", "ball", "field", "game", "hockey"],
    },
    {
        icon: "🏏",
        title: "Cricket Game",
        names: ["Cricket Game", "ball", "bat", "cricket"],
    },
    { icon: "🥍", title: "Lacrosse", names: ["Lacrosse", "ball", "stick"] },
    {
        icon: "⛳",
        title: "Flag in Hole",
        names: ["Flag in Hole", "golf", "hole"],
    },
    {
        icon: "🥊",
        title: "Boxing Glove",
        names: ["Boxing Glove", "boxing", "glove"],
    },
    {
        icon: "🥋",
        title: "Martial Arts Uniform",
        names: ["Martial Arts Uniform", "judo", "karate", "taekwondo"],
    },
    {
        icon: "🎽",
        title: "Running Shirt",
        names: ["Running Shirt", "athletics", "running", "sash"],
    },
    { icon: "🛹", title: "Skateboard", names: ["Skateboard", "board"] },

    // --- Smileys & Expressions ---
    {
        icon: "😀",
        title: "Grinning Face",
        names: ["Grinning Face", "face", "grin", "happy", "smile"],
    },
    {
        icon: "😃",
        title: "Grinning Face with Big Eyes",
        names: ["Grinning Face with Big Eyes", "face", "happy", "joy"],
    },
    {
        icon: "😄",
        title: "Grinning Face with Smiling Eyes",
        names: ["Grinning Face with Smiling Eyes", "face", "happy", "laugh"],
    },
    {
        icon: "😁",
        title: "Beaming Face with Smiling Eyes",
        names: ["Beaming Face with Smiling Eyes", "face", "grin", "teeth"],
    },
    {
        icon: "😆",
        title: "Grinning Squinting Face",
        names: ["Grinning Squinting Face", "face", "laugh", "satisfied"],
    },
    {
        icon: "😅",
        title: "Grinning Face with Sweat",
        names: ["Grinning Face with Sweat", "face", "exercise", "hot", "sweat"],
    },
    {
        icon: "🤣",
        title: "Rolling on the Floor Laughing",
        names: [
            "Rolling on the Floor Laughing",
            "face",
            "floor",
            "laugh",
            "rofl",
        ],
    },
    {
        icon: "😂",
        title: "Face with Tears of Joy",
        names: ["Face with Tears of Joy", "face", "joy", "laugh", "tears"],
    },
    {
        icon: "🙂",
        title: "Slightly Smiling Face",
        names: ["Slightly Smiling Face", "face", "smile"],
    },
    {
        icon: "🙃",
        title: "Upside-Down Face",
        names: ["Upside-Down Face", "face", "silly", "upside-down"],
    },
    {
        icon: "😉",
        title: "Winking Face",
        names: ["Winking Face", "face", "wink"],
    },
    {
        icon: "😊",
        title: "Smiling Face with Smiling Eyes",
        names: ["Smiling Face with Smiling Eyes", "blush", "face", "smile"],
    },
    {
        icon: "😇",
        title: "Smiling Face with Halo",
        names: ["Smiling Face with Halo", "angel", "face", "halo", "innocent"],
    },
    {
        icon: "🥰",
        title: "Smiling Face with Hearts",
        names: [
            "Smiling Face with Hearts",
            "adoration",
            "crush",
            "hearts",
            "love",
        ],
    },
    {
        icon: "😍",
        title: "Smiling Face with Heart-Eyes",
        names: ["Smiling Face with Heart-Eyes", "eye", "face", "love", "smile"],
    },
    {
        icon: "🤩",
        title: "Star-Struck",
        names: ["Star-Struck", "eyes", "face", "star", "excited"],
    },
    {
        icon: "😘",
        title: "Face Blowing a Kiss",
        names: ["Face Blowing a Kiss", "face", "kiss", "love"],
    },
    {
        icon: "😗",
        title: "Kissing Face",
        names: ["Kissing Face", "face", "kiss"],
    },
    {
        icon: "😚",
        title: "Kissing Face with Closed Eyes",
        names: [
            "Kissing Face with Closed Eyes",
            "closed",
            "eyes",
            "face",
            "kiss",
        ],
    },
    {
        icon: "😙",
        title: "Kissing Face with Smiling Eyes",
        names: [
            "Kissing Face with Smiling Eyes",
            "eye",
            "face",
            "kiss",
            "smile",
        ],
    },
    {
        icon: "😋",
        title: "Face Savoring Food",
        names: ["Face Savoring Food", "face", "food", "yum", "delicious"],
    },
    {
        icon: "😛",
        title: "Face with Tongue",
        names: ["Face with Tongue", "face", "tongue"],
    },
    {
        icon: "😜",
        title: "Winking Face with Tongue",
        names: [
            "Winking Face with Tongue",
            "eye",
            "face",
            "joke",
            "tongue",
            "wink",
        ],
    },
    {
        icon: "🤪",
        title: "Zany Face",
        names: ["Zany Face", "eye", "goofy", "large", "small"],
    },
    {
        icon: "😝",
        title: "Squinting Face with Tongue",
        names: [
            "Squinting Face with Tongue",
            "eye",
            "face",
            "horrible",
            "tongue",
        ],
    },
    {
        icon: "🤑",
        title: "Money-Mouth Face",
        names: ["Money-Mouth Face", "banknote", "face", "money", "rich"],
    },
    {
        icon: "🤗",
        title: "Smiling Face with Open Hands",
        names: ["Smiling Face with Open Hands", "face", "hug", "open"],
    },
    {
        icon: "🤫",
        title: "Shushing Face",
        names: ["Shushing Face", "quiet", "shh", "silence"],
    },
    {
        icon: "🤔",
        title: "Thinking Face",
        names: ["Thinking Face", "consider", "face", "think"],
    },
    {
        icon: "🤐",
        title: "Zipper-Mouth Face",
        names: ["Zipper-Mouth Face", "face", "mouth", "zipper"],
    },
    {
        icon: "🤨",
        title: "Face with Raised Eyebrow",
        names: ["Face with Raised Eyebrow", "distrust", "skeptical"],
    },
    {
        icon: "😐",
        title: "Neutral Face",
        names: ["Neutral Face", "deadpan", "face", "neutral"],
    },
    {
        icon: "😑",
        title: "Expressionless Face",
        names: [
            "Expressionless Face",
            "expressionless",
            "face",
            "inexpressive",
        ],
    },
    {
        icon: "😶",
        title: "Face Without Mouth",
        names: ["Face Without Mouth", "face", "mouth", "quiet", "silent"],
    },
    {
        icon: "😏",
        title: "Smirking Face",
        names: ["Smirking Face", "face", "smirk"],
    },
    {
        icon: "😒",
        title: "Unamused Face",
        names: ["Unamused Face", "face", "unamused", "unhappy"],
    },
    {
        icon: "🙄",
        title: "Face with Rolling Eyes",
        names: ["Face with Rolling Eyes", "eyes", "face", "rolling"],
    },
    {
        icon: "😬",
        title: "Grimacing Face",
        names: ["Grimacing Face", "face", "grimace"],
    },
    {
        icon: "🤥",
        title: "Lying Face",
        names: ["Lying Face", "face", "lie", "pinocchio"],
    },
    {
        icon: "😌",
        title: "Relieved Face",
        names: ["Relieved Face", "face", "relieved"],
    },
    {
        icon: "😔",
        title: "Pensive Face",
        names: ["Pensive Face", "dejected", "face", "pensive"],
    },
    {
        icon: "😪",
        title: "Sleepy Face",
        names: ["Sleepy Face", "face", "sleep"],
    },
    {
        icon: "🤤",
        title: "Drooling Face",
        names: ["Drooling Face", "drool", "face"],
    },
    {
        icon: "😴",
        title: "Sleeping Face",
        names: ["Sleeping Face", "face", "sleep", "zzz"],
    },
    {
        icon: "😷",
        title: "Face with Medical Mask",
        names: ["Face with Medical Mask", "doctor", "face", "mask", "sick"],
    },
    {
        icon: "🤒",
        title: "Face with Thermometer",
        names: ["Face with Thermometer", "face", "ill", "sick", "thermometer"],
    },
    {
        icon: "🤕",
        title: "Face with Head-Bandage",
        names: ["Face with Head-Bandage", "bandage", "face", "hurt", "injured"],
    },
    {
        icon: "🤢",
        title: "Nauseated Face",
        names: ["Nauseated Face", "face", "nauseated", "vomit", "sick"],
    },
    {
        icon: "🤮",
        title: "Face Vomiting",
        names: ["Face Vomiting", "sick", "vomit"],
    },
    {
        icon: "🤧",
        title: "Sneezing Face",
        names: ["Sneezing Face", "face", "gesundheit", "sick", "sneeze"],
    },
    {
        icon: "🥵",
        title: "Hot Face",
        names: ["Hot Face", "feverish", "heat stroke", "hot", "sweating"],
    },
    {
        icon: "🥶",
        title: "Cold Face",
        names: ["Cold Face", "blue-faced", "cold", "freezing", "frostbite"],
    },
    {
        icon: "🥴",
        title: "Woozy Face",
        names: ["Woozy Face", "dizzy", "intoxicated", "tipsy", "uneven eyes"],
    },
    {
        icon: "😵",
        title: "Face with Crossed-Out Eyes",
        names: [
            "Face with Crossed-Out Eyes",
            "crossed-out eyes",
            "dead",
            "dizzy",
        ],
    },
    {
        icon: "🤯",
        title: "Exploding Head",
        names: ["Exploding Head", "mind blown", "shocked"],
    },
    {
        icon: "🤠",
        title: "Cowboy Hat Face",
        names: ["Cowboy Hat Face", "cowboy", "face", "hat"],
    },
    {
        icon: "🥳",
        title: "Partying Face",
        names: ["Partying Face", "celebration", "hat", "horn", "party"],
    },
    {
        icon: "😎",
        title: "Smiling Face with Sunglasses",
        names: ["Smiling Face with Sunglasses", "cool", "face", "sunglasses"],
    },
    {
        icon: "🤓",
        title: "Nerd Face",
        names: ["Nerd Face", "face", "geek", "nerd"],
    },
    {
        icon: "🧐",
        title: "Face with Monocle",
        names: ["Face with Monocle", "monocle", "stuffy"],
    },
    {
        icon: "😕",
        title: "Confused Face",
        names: ["Confused Face", "confused", "face"],
    },
    {
        icon: "😟",
        title: "Worried Face",
        names: ["Worried Face", "face", "worried"],
    },
    {
        icon: "🙁",
        title: "Slightly Frowning Face",
        names: ["Slightly Frowning Face", "face", "frown"],
    },
    {
        icon: "😮",
        title: "Face with Open Mouth",
        names: ["Face with Open Mouth", "face", "mouth", "open", "sympathy"],
    },
    {
        icon: "😯",
        title: "Hushed Face",
        names: ["Hushed Face", "face", "hushed", "surprised"],
    },
    {
        icon: "😲",
        title: "Astonished Face",
        names: ["Astonished Face", "astonished", "face", "shocked"],
    },
    {
        icon: "😳",
        title: "Flushed Face",
        names: ["Flushed Face", "dazed", "face", "flushed"],
    },
    {
        icon: "🥺",
        title: "Pleading Face",
        names: ["Pleading Face", "begging", "mercy", "puppy dog eyes"],
    },
    {
        icon: "😦",
        title: "Frowning Face with Open Mouth",
        names: ["Frowning Face with Open Mouth", "face", "frown", "mouth"],
    },
    {
        icon: "📁",
        title: "File Folder",
        names: ["File Folder", "file", "folder", "office"],
    },
    {
        icon: "📂",
        title: "Open File Folder",
        names: ["Open File Folder", "file", "folder", "open"],
    },
    {
        icon: "📄",
        title: "Page Facing Up",
        names: ["Page Facing Up", "document", "page", "paper"],
    },
    { icon: "📅", title: "Calendar", names: ["Calendar", "date", "schedule"] },
    {
        icon: "📊",
        title: "Bar Chart",
        names: ["Bar Chart", "bar", "chart", "graph", "stats"],
    },
    {
        icon: "📋",
        title: "Clipboard",
        names: ["Clipboard", "clipboard", "notes"],
    },
    { icon: "📌", title: "Pushpin", names: ["Pushpin", "pin", "location"] },
    {
        icon: "📍",
        title: "Round Pushpin",
        names: ["Round Pushpin", "pin", "location", "mark"],
    },
    {
        icon: "📎",
        title: "Paperclip",
        names: ["Paperclip", "attachment", "clip"],
    },
    {
        icon: "📏",
        title: "Straight Ruler",
        names: ["Straight Ruler", "ruler", "straightedge"],
    },
    {
        icon: "📐",
        title: "Triangular Ruler",
        names: ["Triangular Ruler", "ruler", "triangle"],
    },
    { icon: "✂️", title: "Scissors", names: ["Scissors", "cut", "tool"] },

    // --- Nature, Weather & Animals ---
    { icon: "☀️", title: "Sun", names: ["Sun", "bright", "sunny", "weather"] },
    {
        icon: "🌙",
        title: "Crescent Moon",
        names: ["Crescent Moon", "crescent", "moon", "night", "space"],
    },
    { icon: "⭐", title: "Star", names: ["Star", "night", "sky", "space"] },
    {
        icon: "🌟",
        title: "Glowing Star",
        names: ["Glowing Star", "glitter", "sparkle", "star"],
    },
    {
        icon: "✨",
        title: "Sparkles",
        names: ["Sparkles", "clean", "magic", "sparkle"],
    },
    {
        icon: "⚡",
        title: "Lightning",
        names: ["Lightning", "bolt", "electricity", "storm"],
    },
    { icon: "☁️", title: "Cloud", names: ["Cloud", "cloudy", "weather"] },
    {
        icon: "🌧️",
        title: "Cloud with Rain",
        names: ["Cloud with Rain", "cloud", "rain", "weather"],
    },
    {
        icon: "❄️",
        title: "Snowflake",
        names: ["Snowflake", "cold", "snow", "weather"],
    },
    { icon: "🌈", title: "Rainbow", names: ["Rainbow", "rain", "weather"] },
    {
        icon: "🌊",
        title: "Water Wave",
        names: ["Water Wave", "ocean", "sea", "wave"],
    },
    {
        icon: "🌸",
        title: "Cherry Blossom",
        names: ["Cherry Blossom", "blossom", "cherry", "flower", "spring"],
    },
    { icon: "🌹", title: "Rose", names: ["Rose", "flower", "love", "red"] },
    { icon: "🌻", title: "Sunflower", names: ["Sunflower", "flower", "sun"] },
    {
        icon: "🌱",
        title: "Seedling",
        names: ["Seedling", "plant", "young", "sprout"],
    },
    {
        icon: "🌲",
        title: "Evergreen Tree",
        names: ["Evergreen Tree", "tree", "wood"],
    },
    {
        icon: "🌳",
        title: "Deciduous Tree",
        names: ["Deciduous Tree", "tree", "wood"],
    },
    {
        icon: "🌴",
        title: "Palm Tree",
        names: ["Palm Tree", "palm", "tree", "tropical"],
    },
    { icon: "🌵", title: "Cactus", names: ["Cactus", "desert", "plant"] },
    {
        icon: "🐶",
        title: "Dog Face",
        names: ["Dog Face", "dog", "pet", "puppy"],
    },
    {
        icon: "🐱",
        title: "Cat Face",
        names: ["Cat Face", "cat", "pet", "kitten"],
    },
    {
        icon: "🐭",
        title: "Mouse Face",
        names: ["Mouse Face", "mouse", "rodent"],
    },
    {
        icon: "🐹",
        title: "Hamster Face",
        names: ["Hamster Face", "hamster", "pet"],
    },
    {
        icon: "🐰",
        title: "Rabbit Face",
        names: ["Rabbit Face", "bunny", "rabbit"],
    },
    { icon: "🦊", title: "Fox", names: ["Fox", "animal", "nature"] },
    { icon: "🐻", title: "Bear", names: ["Bear", "animal", "wild"] },
    { icon: "🐼", title: "Panda", names: ["Panda", "bear", "china"] },
    { icon: "🐨", title: "Koala", names: ["Koala", "australia", "bear"] },
    { icon: "🐯", title: "Tiger Face", names: ["Tiger Face", "tiger", "wild"] },
    { icon: "🦁", title: "Lion", names: ["Lion", "king", "wild"] },
    { icon: "🐮", title: "Cow Face", names: ["Cow Face", "cow", "farm"] },
    { icon: "🐷", title: "Pig Face", names: ["Pig Face", "farm", "pig"] },
    { icon: "🐸", title: "Frog", names: ["Frog", "amphibian"] },
    { icon: "🐵", title: "Monkey Face", names: ["Monkey Face", "monkey"] },
    { icon: "🐔", title: "Chicken", names: ["Chicken", "bird", "farm"] },
    { icon: "🐧", title: "Penguin", names: ["Penguin", "bird", "ice"] },
    { icon: "🐦", title: "Bird", names: ["Bird", "animal", "fly"] },
    { icon: "🦅", title: "Eagle", names: ["Eagle", "bird", "fly"] },
    { icon: "🦆", title: "Duck", names: ["Duck", "bird"] },
    { icon: "🦉", title: "Owl", names: ["Owl", "bird", "night", "wise"] },
    { icon: "🦇", title: "Bat", names: ["Bat", "vampire", "night"] },
    { icon: "🐺", title: "Wolf", names: ["Wolf", "wild", "animal"] },
    { icon: "🐗", title: "Boar", names: ["Boar", "wild"] },
    { icon: "🐴", title: "Horse Face", names: ["Horse Face", "horse"] },
    { icon: "🦄", title: "Unicorn", names: ["Unicorn", "fantasy", "magic"] },
    {
        icon: "🐝",
        title: "Honeybee",
        names: ["Honeybee", "bee", "bug", "insect"],
    },
    { icon: "🐛", title: "Bug", names: ["Bug", "insect"] },
    {
        icon: "🦋",
        title: "Butterfly",
        names: ["Butterfly", "insect", "pretty"],
    },
    { icon: "🐌", title: "Snail", names: ["Snail", "slow"] },
    {
        icon: "🐞",
        title: "Lady Beetle",
        names: ["Lady Beetle", "bug", "ladybug"],
    },
    { icon: "🐜", title: "Ant", names: ["Ant", "bug", "insect"] },
    {
        icon: "🦟",
        title: "Mosquito",
        names: ["Mosquito", "bug", "fever", "malaria"],
    },
    { icon: "🐢", title: "Turtle", names: ["Turtle", "slow", "tortoise"] },
    { icon: "🐍", title: "Snake", names: ["Snake", "reptile"] },
    { icon: "🦎", title: "Lizard", names: ["Lizard", "reptile"] },
    {
        icon: "🦖",
        title: "T-Rex",
        names: ["T-Rex", "dinosaur", "tyrannosaurus"],
    },
    { icon: "🐙", title: "Octopus", names: ["Octopus", "sea"] },
    { icon: "🦑", title: "Squid", names: ["Squid", "sea"] },
    { icon: "🦐", title: "Shrimp", names: ["Shrimp", "food", "seafood"] },
    {
        icon: "🦞",
        title: "Lobster",
        names: ["Lobster", "bisque", "claws", "seafood"],
    },
    { icon: "🦀", title: "Crab", names: ["Crab", "cancer", "claws"] },
    { icon: "🐡", title: "Blowfish", names: ["Blowfish", "fish"] },
    { icon: "🐠", title: "Tropical Fish", names: ["Tropical Fish", "fish"] },
    { icon: "🐟", title: "Fish", names: ["Fish", "seafood"] },
    { icon: "🐬", title: "Dolphin", names: ["Dolphin", "sea"] },
    { icon: "🐳", title: "Spouting Whale", names: ["Spouting Whale", "whale"] },
    { icon: "🦈", title: "Shark", names: ["Shark", "fish", "ocean"] },
    { icon: "🦭", title: "Seal", names: ["Seal", "sea"] },

    // --- Symbols, Objects & Flags ---
    {
        icon: "❤️",
        title: "Red Heart",
        names: ["Red Heart", "heart", "love", "red"],
    },
    {
        icon: "🧡",
        title: "Orange Heart",
        names: ["Orange Heart", "heart", "orange"],
    },
    {
        icon: "💛",
        title: "Yellow Heart",
        names: ["Yellow Heart", "heart", "yellow"],
    },
    {
        icon: "💚",
        title: "Green Heart",
        names: ["Green Heart", "green", "heart"],
    },
    { icon: "💙", title: "Blue Heart", names: ["Blue Heart", "blue", "heart"] },
    {
        icon: "💜",
        title: "Purple Heart",
        names: ["Purple Heart", "heart", "purple"],
    },
    {
        icon: "🖤",
        title: "Black Heart",
        names: ["Black Heart", "black", "heart"],
    },
    {
        icon: "🤍",
        title: "White Heart",
        names: ["White Heart", "heart", "white"],
    },
    {
        icon: "🤎",
        title: "Brown Heart",
        names: ["Brown Heart", "brown", "heart"],
    },
    {
        icon: "💔",
        title: "Broken Heart",
        names: ["Broken Heart", "break", "broken", "heart"],
    },
    {
        icon: "❣️",
        title: "Heart Exclamation",
        names: ["Heart Exclamation", "exclamation", "heart"],
    },
    {
        icon: "💕",
        title: "Two Hearts",
        names: ["Two Hearts", "hearts", "love"],
    },
    {
        icon: "💞",
        title: "Revolving Hearts",
        names: ["Revolving Hearts", "hearts", "revolving"],
    },
    {
        icon: "💓",
        title: "Beating Heart",
        names: ["Beating Heart", "beating", "heartbeat"],
    },
    {
        icon: "💗",
        title: "Growing Heart",
        names: ["Growing Heart", "growing", "heart"],
    },
    {
        icon: "💖",
        title: "Sparkling Heart",
        names: ["Sparkling Heart", "sparkle", "heart"],
    },
    {
        icon: "💘",
        title: "Heart with Arrow",
        names: ["Heart with Arrow", "arrow", "cupid"],
    },
    {
        icon: "💝",
        title: "Heart with Ribbon",
        names: ["Heart with Ribbon", "ribbon", "valentine"],
    },
    {
        icon: "💯",
        title: "Hundred Points",
        names: ["Hundred Points", "100", "full", "score"],
    },
    {
        icon: "💢",
        title: "Anger Symbol",
        names: ["Anger Symbol", "angry", "comic"],
    },
    {
        icon: "💬",
        title: "Speech Balloon",
        names: ["Speech Balloon", "bubble", "chat", "message"],
    },
    {
        icon: "👁️‍🗨️",
        title: "Eye in Speech Bubble",
        names: ["Eye in Speech Bubble", "witness", "speech"],
    },
    {
        icon: "🗯️",
        title: "Right Anger Bubble",
        names: ["Right Anger Bubble", "angry", "bubble"],
    },
    {
        icon: "💭",
        title: "Thought Balloon",
        names: ["Thought Balloon", "bubble", "thought"],
    },
    { icon: "💤", title: "ZZZ", names: ["ZZZ", "asleep", "sleep"] },
    {
        icon: "♨️",
        title: "Hot Springs",
        names: ["Hot Springs", "springs", "steaming"],
    },
    {
        icon: "🛑",
        title: "Stop Sign",
        names: ["Stop Sign", "octagonal", "stop"],
    },
    {
        icon: "🕛",
        title: "Twelve O'Clock",
        names: ["Twelve O'Clock", "12:00", "clock", "noon"],
    },
    {
        icon: "⚠️",
        title: "Warning",
        names: ["Warning", "alert", "danger", "warning"],
    },
    {
        icon: "🚫",
        title: "Prohibited",
        names: ["Prohibited", "ban", "forbidden", "no"],
    },
    {
        icon: "✅",
        title: "Check Mark Button",
        names: ["Check Mark Button", "check", "mark", "yes"],
    },
    {
        icon: "❌",
        title: "Cross Mark",
        names: ["Cross Mark", "cancel", "cross", "no", "x"],
    },
    {
        icon: "⭕",
        title: "Heavy Large Circle",
        names: ["Heavy Large Circle", "circle", "o"],
    },
    { icon: "🔴", title: "Red Circle", names: ["Red Circle", "circle", "red"] },
    {
        icon: "🔵",
        title: "Blue Circle",
        names: ["Blue Circle", "blue", "circle"],
    },
    {
        icon: "⬛",
        title: "Black Large Square",
        names: ["Black Large Square", "black", "square"],
    },
    {
        icon: "⬜",
        title: "White Large Square",
        names: ["White Large Square", "square", "white"],
    },
    {
        icon: "🔒",
        title: "Locked",
        names: ["Locked", "lock", "padlock", "secure", "security"],
    },
    {
        icon: "🔓",
        title: "Unlocked",
        names: ["Unlocked", "lock", "open", "padlock"],
    },
    {
        icon: "🔏",
        title: "Locked with Pen",
        names: ["Locked with Pen", "lock", "ink", "privacy"],
    },
    {
        icon: "🔐",
        title: "Locked with Key",
        names: ["Locked with Key", "key", "lock", "secure"],
    },
    { icon: "🔑", title: "Key", names: ["Key", "lock", "password"] },
    { icon: "🗝️", title: "Old Key", names: ["Old Key", "clue", "key", "old"] },
    { icon: "🔨", title: "Hammer", names: ["Hammer", "tool", "work"] },
    { icon: "🪓", title: "Axe", names: ["Axe", "chop", "tool", "wood"] },
    { icon: "⛏️", title: "Pick", names: ["Pick", "mining", "tool"] },
    {
        icon: "🛠️",
        title: "Hammer and Wrench",
        names: ["Hammer and Wrench", "fix", "repair", "tools"],
    },
    { icon: "🗡️", title: "Dagger", names: ["Dagger", "knife", "weapon"] },
    {
        icon: "⚔️",
        title: "Crossed Swords",
        names: ["Crossed Swords", "battle", "swords", "weapon"],
    },
    { icon: "💣", title: "Bomb", names: ["Bomb", "explosive"] },
    {
        icon: "🛡️",
        title: "Shield",
        names: ["Shield", "defense", "protect", "security"],
    },
    { icon: "🚬", title: "Cigarette", names: ["Cigarette", "smoking"] },
    { icon: "⚰️", title: "Coffin", names: ["Coffin", "death", "die"] },
    { icon: "🏺", title: "Amphora", names: ["Amphora", "jar", "vase"] },
    { icon: "🗺️", title: "World Map", names: ["World Map", "map", "world"] },
    { icon: "🧱", title: "Brick", names: ["Brick", "clay", "wall"] },
    { icon: "💈", title: "Barber", names: ["Barber", "hair", "salon"] },
    {
        icon: "🧯",
        title: "Fire Extinguisher",
        names: ["Fire Extinguisher", "extinguish", "fire", "quench"],
    },
    {
        icon: "🎁",
        title: "Wrapped Gift",
        names: ["Wrapped Gift", "box", "gift", "present", "reward"],
    },
    {
        icon: "🎈",
        title: "Balloon",
        names: ["Balloon", "celebration", "party"],
    },
    {
        icon: "🎉",
        title: "Party Popper",
        names: ["Party Popper", "celebration", "confetti", "party"],
    },
    {
        icon: "🎊",
        title: "Confetti Ball",
        names: ["Confetti Ball", "ball", "celebration", "confetti"],
    },
    {
        icon: "🎏",
        title: "Carp Streamer",
        names: ["Carp Streamer", "carp", "streamer"],
    },
    { icon: "🎀", title: "Ribbon", names: ["Ribbon", "bow", "celebration"] },
    { icon: "🪙", title: "Token", names: ["Token", "coin", "gold"] },
    {
        icon: "🏁",
        title: "Chequered Flag",
        names: ["Chequered Flag", "checkered", "flag", "finish", "race"],
    },
    {
        icon: "🚩",
        title: "Triangular Flag",
        names: ["Triangular Flag", "flag", "post"],
    },
    {
        icon: "🏴‍☠️",
        title: "Pirate Flag",
        names: ["Pirate Flag", "flag", "pirate", "skull"],
    },
];

export default emojis;
